### DISCUSSION TITLE
Gitlab CI usage

### DISCUSSION THREAD

**Discussion by BlueskyFR** [helmwave/helmwave#1084] [Q&A]
Hi!

The docs aren't clear on that point so I am asking the question here: how is Helmwave expecting to get the context from Gitlab CI?

The agent provides a `$KUBECONFIG` env var but that's all, and `kubectl` isn't available from the **helmwave** docker image.

So that leaves me wondering: what is the expected approach in order to select the context?

Thanks in advance!

**Comment by zhilyaev** [comment]
Hi! Here's how Helmwave typically handles kubeconfig and context selection when running in a CI/CD pipeline like GitLab CI:

 -   Environment Variable $KUBECONFIG: Helmwave relies on the $KUBECONFIG environment variable to determine which kubeconfig file to use. If your GitLab CI/CD agent is already providing this variable (e.g., pointing to the kubeconfig file), Helmwave should be able to use it directly.
 - default path ~/.kube/config

```yaml
deploy:
  image: ghcr.io/helmwave/helmwave
  script:
    - helmwave up
  variables:
    KUBECONFIG: /path/to/kubeconfig

```
 
you can use different kube contexts in helmwave.yml

https://docs.helmwave.app/0.41.x/yaml/?h=context#context
