### DISCUSSION TITLE
Helmwave v1.0.0

### DISCUSSION THREAD

**Discussion by zhilyaev** [helmwave/helmwave#1120] [Ideas]
# helmwave.yml

It's not a final! Just the current developed version.

```yaml
project: example
version: 1.0.0

repositories:
  bitnami: https://charts.bitnami.com/bitnami

registries:
  ghcr.io: {}

defaults:
  # Default fields for all releases
  release:
    chart: bitnami/nginx
    namespace: default
    context: my-kube-context

  # Default fields for all registry
  registry:
    insecure: false

  # Default fields for all registry
  repository:
    insecure: false


releases:
  nginx@example@custom-context:
    version: 0.3.0

  nginx@hello: # = nginx@hello@my-kube-context
    version: 0.1.0

  nginx: # = nginx@default@my-kube-context
    version: 0.2.0
```

**Comment by zhilyaev** [comment]
# Graph of Kubernetes structures dependencies
![Image](https://github.com/user-attachments/assets/af38c3bd-4c83-4f93-8476-2fe90343ea17)

// todo: add url

# Components 

<img width="1434" alt="Image" src="https://github.com/user-attachments/assets/32e94abc-a8c9-43a5-b0e3-f1c2ea41d081" />

**Comment by zhilyaev** [comment]
# Repositories vs Registries?

## V1

2 different types.

```yaml
repositories:
  bitnami: https://charts.bitnami.com/bitnami

registries:
  ghcr.io: {}
```

## V2

Merge Repositories & Repositories into one spec.

```yaml
repositories:
  bitnami: https://charts.bitnami.com/bitnami
  ghcr.io: oci://ghcr.io
```

**Reply by zhilyaev** [reply]
V1

**Reply by zhilyaev** [reply]
V2

**Comment by zhilyaev** [comment]
# Tags vs Labels?
Labels!

```yaml
releases:
  app@prod:
    labels:
      env: prod

  db@prod:
    labels:
      env: prod


  app@stage:
    labels:
      env: stage

  db@stage:
    labels:
      env: stage
```

`$ helmwave build --labels env=prod`
`$ helmwave build --labels env=stage`

## Label Logic

!!! Looking for solutions

### glob:

- `$ helmwave build --labels env=pro?`
- `$ helmwave build --labels branch=feature/*`

### RE
- `$ helmwave build --labels branch=~ /feature/i`
- `$ helmwave build -l env=(prod|stage)`

### expressions, = , !=, >, <, ?

- `$ helmwave build --labels env!=stage`
- `$ helmwave build --labels lvl>0`

**Reply by tony-engineering** [reply]
I like the ability to filter which releases with several tags. From my understanding it is currently not possible to perform AND operation with tags https://helmwave.readthedocs.io/en/latest/examples/tags/?h=tags . Why don't we just keep tags but enhance the possibilities ? 

I am currently doing like that to select stages:
```
CI_ENVIRONMENT_NAME=prod helmwave build --yml --plandir .helmwave.prod --tags=yace-exporter
```
and in the code:
```
{{ if eq (requiredEnv "CI_ENVIRONMENT_NAME") "prod" }}
  - name: yace-exporter
    namespace: monitoring
    create_namespace: true
    wait: true
    timeout: 1m
    max_history: 3
    tags:
      - yace-exporter
      - non-critical
    chart:
      name: nerdswords/yet-another-cloudwatch-exporter
      version: {{ $versions | get "versions.yace" "" }}
    values:
      - values/yace/_.yaml
      - values/yace/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}.yaml
{{ end }}
```

**Reply by zhilyaev** [reply]
@tony-engineering did you try HELMWAVE_MATCH_ALL_TAGS?

**Comment by zhilyaev** [comment]
# Values


## V1

Non-map.

```yaml
values:
  - s3://mybucket/config/file.json
  - ../path/to/values.json
  - src: git+https://github.com/hairyhenderson/gomplate//docs-src/content/functions/values.yml
    alias: gitfile
```

## V2

URL is a key. 

```yaml
values:
  "https://raw.githubusercontent.com/my.store.yml":
    alias: my-store
    render: sops
```


## V3

Alias is a key. 
```yaml
values:
  my:
    src: https://raw.githubusercontent.com/my.yml
    render: sops
```

--- 
The third way looks good.

**Reply by zhilyaev** [reply]
V1

**Reply by zhilyaev** [reply]
V2

**Reply by zhilyaev** [reply]
V3

**Reply by tony-engineering** [reply]
does v3 means that this code
```yaml
  - name: kube-prometheus
    namespace: monitoring
    create_namespace: true
    wait: true
    timeout: 5m
    max_history: 3
    tags:
      - prometheus
      - critical
    chart:
      name: bitnami/kube-prometheus # oci://registry-1.docker.io/bitnamicharts/kube-prometheus
      version: {{ $versions | get "versions.kube-prometheus" "" }}
    values:
      - values/kube-prometheus/_.yaml
      - src: values/kube-prometheus/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}.yaml
        renderer: copy
```
would become 
```yaml
  - name: kube-prometheus
    namespace: monitoring
    create_namespace: true
    wait: true
    timeout: 5m
    max_history: 3
    tags:
      - prometheus
      - critical
    chart:
      name: bitnami/kube-prometheus # oci://registry-1.docker.io/bitnamicharts/kube-prometheus
      version: {{ $versions | get "versions.kube-prometheus" "" }}
    values:
      global:
        values/kube-prometheus/_.yaml
      env-specific:
        src: values/kube-prometheus/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}.yaml
        renderer: copy
```
?

**Reply by zhilyaev** [reply]
@tony-engineering. Not at all. A little update. I will use the V5 spec for FileRef to explain.

```yaml
values:
      global:
        values/kube-prometheus/_.yaml # it is not correct syntax.
      env-specific: # ok
        src: values/kube-prometheus/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}.yaml
        renderer: copy
```

Pretty Example for V5:

```yaml
values:
      # *.tpl –> run gomplate render
      global.tpl: values/kube-prometheus/_.yaml
      # copy
      env-specific: values/kube-prometheus/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}.yaml
```

Full Example for V5:

```yaml
values:
      # *.tpl –> run gomplate render
      global.tpl: 
        src: values/kube-prometheus/_.yaml
      # copy
      env-specific:  
        src: values/kube-prometheus/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}.yaml
```

**Reply by r3nic1e** [reply]
In general yaml maps/dicts are not ordered but for helm values order really matter. So I prefer having an order-specific list here just in case YAML decoder will do something not expected here.

**Comment by zhilyaev** [comment]
# StoreFiles

```yaml
releases:
  app:
    storefiles:
      my: # <--- this is an alias
        src: https://raw.githubusercontent.com/my.store.yml
        render: sops
    values:
      a: # <--- this is an alias
        src: a.values.yml
        render: copy
      b: # <--- this is an alias
        src: b.values.yml
        render: copy
```

## How to call the data from the store?

`$ cat a.values.yml`

```yaml
podLabels:
  name: (ds "store/my").bla
```

Get any stores by datasource by `store/$store_alias`

## How to call the data from another value?

!!! You can face a problem with cyclic dependencies.

`$ cat b.values.yml`

```yaml
podLabels:
  name: (ds "values/a").bla
```

Get any values by datasource by `values/$values_alias`

**Comment by zhilyaev** [comment]
# Defaults

#963, #924, #925, #266, #1104 

Defaults can be passed by `helmwave.yml` or environment variables. 
helmwave has a lot of features and settings that can interact with each other. 
That's why we want to keep it once inside the `helmwave.yml` defaults section.

Any fields in this section can be passed by ENVIRONMENT VARIABLES.

## Example 

- `export HELMWAVE_DEFAULTS_GOMLATE_RIGHT=']]'`
- `cat helmwave.yml`

```yaml
defaults:
  gomplate:
    leftDelim: '[['
    rightDelim: ']]'

```

It's equal to

`cat helmwave.yml`
```yaml
defaults:
  gomplate:
    leftDelim: '[['
```

**Comment by zhilyaev** [comment]
# Gomplate vs Sprig?
Gomplate!

Sprig must die.

**Comment by zhilyaev** [comment]
# Slice or Map?
Map!

```yaml
releases:
- name: foo
- name: bar
```

```yaml
releases:
  foo: 
  bar:
```

It's prettier for yaml merge and finding the uniqname problems.

**Reply by tony-engineering** [reply]
From my perspective there is no big difference

**Comment by zhilyaev** [comment]
# Magic Uniqname
Uniqname is `$release_name@$namespace@kubecontext` in one string. It helps helmwave to understand the destination of your stack.

## V1 
```yaml
releases:
  nginx@example@custom-context:
    version: 0.3.0

  nginx@hello: # = nginx@hello@my-shell-kube-context
    version: 0.1.0

  nginx: # = nginx@default@my-shell-kube-context
    version: 0.2.0
```

- If kubecontext is empty, helmwave would use your current kubeconfig to understand it.
- If kubecontext is empty, helmwave would use your current kubeconfig to understand it.
- The release name is always required.

Issues:
- If Helmwave uses the kubeconfig default value. And a user changed their context after building a plan. Helmwave has a chance to fail.

## V2

If you escalate to a new scope, you should also provide a new context for the uniqname.

### Uniqname is only a name
```yaml
releases:
  nginx: {} # ok
  redis: {} # ok
```


### Uniqname escalates to namespace

If one of the releases has a namespace, it means everyone should have a namespace. 

```yaml
releases:
  nginx@prod: {} # prod is a namespace
  redis@stage: {} # stage is a namespace

  my: {} # err invalid, namespace not defined.
```

### Uniqname escalates to kubecontext

If one of the releases has a kubecontext, it means everyone should have a kubecontext. 


```yaml
releases:
  nginx@default@stage: {} # stage is a kubecontext
  nginx@default@prod : {} # prod is a kubecontext

  my: {} # err invalid, namespace and kubecontext not defined.
  my@default: {} # err invalid, namespace not defined.
```

**Reply by zhilyaev** [reply]
V1

**Reply by zhilyaev** [reply]
V2

**Reply by tony-engineering** [reply]
I like the idea of making helmwave aware of the kubecontext. It happened to me sometilmes to deploy to the wrong cluster, or being confused because the helmwave build command is showing diff between non-prod and prod cluster... 
its a pain to always need to verify kubecontext before building

**Comment by zhilyaev** [comment]
# Deploy manifests step-by-step



## Order by weight

#1100 


```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-by-weight
  annotations:
    "helmwave.app/weight": "1"
```

```mermaid
flowchart LR
    subgraph weight_0
      configmap_A
      configmap_B
    end

    weight_0 --> weight_1

    subgraph weight_1
      deployment_A
      deployment_B
    end
```

### Issues
- Helmwave should use Nelm. Like that: https://github.com/werf/nelm/tree/main#advanced-resource-ordering

## Order by Needs

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: order-by-needs
  annotations:
    "helmwave.app/needs": "configMap/order-by-weight,<$kind>/<$name>"
```

```mermaid
flowchart LR
      configmap_A --> deployment_A
      configmap_B --> deployment_B


```

### Issues
- Helmwave must patch the original Helm package. Nelm doesn't have this feature yet. 
- Cyclic dependencies
- Should helmwave check probes for workloads? 
- Could you get the status resource ready?

**Reply by w33dw0r7d** [reply]
What problem do these changes solve? Helm has a resource queue.

**Reply by zhilyaev** [reply]
@w33dw0r7d Helm has hooks. It's not a real step-by-step. Cause hooks are not part of the helm release. Hooks are crutches. Hooks are a disgusting design to achieve a queue feature.

**Reply by w33dw0r7d** [reply]
Helm installs resources in the following order:

Namespace
NetworkPolicy
ResourceQuota
LimitRange
PodSecurityPolicy
PodDisruptionBudget
ServiceAccount
Secret
SecretList
ConfigMap
StorageClass
PersistentVolume
PersistentVolumeClaim
CustomResourceDefinition
ClusterRole
ClusterRoleList
ClusterRoleBinding
ClusterRoleBindingList
Role
RoleList
RoleBinding
RoleBindingList
Service
DaemonSet
Pod
ReplicationController
ReplicaSet
Deployment
HorizontalPodAutoscaler
StatefulSet
Job
CronJob
Ingress
APIService

**Reply by zhilyaev** [reply]
@w33dw0r7d 
What should I do if I need `deployment-a --> deployment-b` . Suppose I have a frontend and a backend. Frontend (A) can't start without Backend (B)?

**Reply by w33dw0r7d** [reply]
Make two releases with depends_on.

**Reply by zhilyaev** [reply]
It's a good choice, but sometimes we have cases. Where engineers can't divide it into 2 releases.

**Reply by w33dw0r7d** [reply]
What cases?

**Reply by zhilyaev** [reply]
1. Existing charts that you do not own. 
2. You don't have the resources to split it.
3. Specific logic for a release. Well, you can take a look at the gitlab/gitlab chart. Or let me continue with my previous example.
```mermaid
graph LR
deployment-a --> deployment-b
service-account & configmap --> deployment-a & deployment-b
```

Both deployments need the same resources. But we will split it into 2. It means one of them became an owner. That's a bad pattern. And then you also need to describe the names of existing resources in your second release. This is pain.

**Comment by zhilyaev** [comment]
# Levels of abstraction

```mermaid
flowchart TD
    configmap_A & deployment_A & service_A & ingress_A --> helm_chart_A
    configmap_B & deployment_B & service_B & ingress_B --> helm_chart_B
    helm_chart_A --> release_A1 & release_A2 --> helmwave
    helm_chart_B --> release_B1 & release_B2 --> helmwave
```

**Comment by zhilyaev** [comment]
# Deploy releases step-by-step

#1022 , #734 

## Strict needs

```yaml
releases:
  app:
    needs:
       namespace:
         prod: {}
       name:
           db: {}
       labels:
           app: db
```

### Issues
- How to manage OR & AND operators?
- How to manage app: prod-*, etc?

## Smart needs

```yaml
releases:
  app:
    needs:
       my-rule-name:
         - namespace = "prod" and name = "db" and label.app = "db"
```

### Issues

- SQLite is too much.
- How to use Kubernetes labels for specific usage?

**Comment by zhilyaev** [comment]
# Client-Side Apply (CSA) vs Server-Side Apply (SSA)

Server-Side Apply!

#1100

**Comment by zhilyaev** [comment]
# How to choose a render?

#1017 , #1018 

## V1 

Create an additional field where users can set a render.

```yaml
files:
    my:
      src: 
        url: https://raw.githubusercontent.com/my.yml
      render: sops
```

## V2

KISS, it's the users' responsibility. 

Users can use [Overriding MIME Types](https://docs.gomplate.ca/datasources/#overriding-mime-types)

`type=text/plain` can force disable Gomplate

```yaml
files:
    only-copy-file:
      src:  https://raw.githubusercontent.com/my.yml?type=text/plain
   render-and-copy:
      src: https://raw.githubusercontent.com/my.yml
   sops-and-copy:
      src: https://raw.githubusercontent.com/my.yml?type=text/sops # create custom MIME types for specific usage.
```


## V3

Use Headers to pass options

```yaml
files:
    only-copy-file:
      src: 
        url: https://raw.githubusercontent.com/my.yml
        header:
          x-bla-type: text/plain  # create custom header
   render-and-copy:
      src: 
        url: https://raw.githubusercontent.com/my.yml
   sops-and-copy:
      src: 
        url: https://raw.githubusercontent.com/my.yml
        header:
          x-bla-type: text/sops # create custom header with custom values
```


## V4

Define options by extensions?

If a file extension is `tpl`, Gomplate will run the render.

If a file extension is `sops.yml`, Gomplate will run the sops.

The default behavior is just to copy.

```yaml
files:
    only-copy-file:
      src:  https://raw.githubusercontent.com/my.yml
   render-and-copy:
      src: https://raw.githubusercontent.com/my.yml.tpl
   sops-and-copy:
      src: https://raw.githubusercontent.com/my.sops.yml
```

## V5

like V4, but extensions defined in aliases.

```yaml
files:
    my.yml: # <-- just copy
      src:  https://raw.githubusercontent.com/my.txt
   my.yml.tpl: # <-- render and copy
      src: https://raw.githubusercontent.com/my.txt
   my.yml.sops: # <-- sops and copy
      src: https://raw.githubusercontent.com/my.txt
```

--- 

The easiest way to understand is V1 or V4.

**Reply by zhilyaev** [reply]
V5 
https://github.com/helmwave/fileref has implemented V5

**Reply by zhilyaev** [reply]
V1

**Reply by zhilyaev** [reply]
V2

**Reply by zhilyaev** [reply]
V3

**Reply by zhilyaev** [reply]
V4

**Comment by zhilyaev** [comment]
# Pull or Push model CD?
**Together!**


#740, #739 , #736


Helmwave transform `helmwave.yml` into plandir.
Plandir contains CRD helmwave manifests. The most Important is a `kind: Plan`.  Then helmwave reads `kind: Plan` to get information about what helmwave should do. You can push that plan locally. Or install helmwave-operator. Then the helmwave operator will listen to CRD helmwave manifests.

![Image](https://github.com/user-attachments/assets/6855fba6-5f7f-4148-a4be-0f4ccec5b876)

<img width="1406" alt="Image" src="https://github.com/user-attachments/assets/c7c8209b-2cd2-40d1-91db-dbc0f7dc5d50" />

!!! Plan dir structure and specification in progress. 

## Release

```yaml
api: helmwave.app/v1alpha1
kind: Release
metadata:
  name: nginx-a
  namespace: default
spec:
  chart: 
    name: oci://ghcr:io/nginx
    version: 1.0.0

```

## Repository

```yaml
api: helmwave.app/v1alpha1
kind: Repository
metadata:
  name: ghcr
  namespace: default
spec:
  insecure: false
  url: oci://ghcr.io
```

## Plan

```yaml
api: helmwave.app/v1alpha1
kind: Plan
spec: ...


```

**Comment by tony-engineering** [comment]
# Version pinning ?

Nice suggestions, but I think we miss a very important feature: version pinning. Its a bad practice to always take the latest version of a chart, its safer to update charts manually. Or have a system where only patch versions are update automatically. Helm and Helmfile tool are supporting this https://helm.sh/docs/chart_best_practices/dependencies/#versions .
I worked around it by doing this:

charts.lock.yaml
```
# In this file you can pin versions
# Gitlab CI check-for-updates job will request manual
# change if new version is available
versions:
  grafana: "8.10.3"
  yace: "0.38.0"
  karpenter: "1.3.2"
  kube-prometheus: "9.6.3"
  metrics-server:  "3.12.2"
  alb-controller: "1.11.0"
  ingress-nginx: "4.12.0"
  aws-for-fluent-bit: "0.1.35"
  kube-janitor: "0.3.1"
  mlflow-postgres: "13.2.30"
  mlflow: "0.7.19"
```

always get version like this in helmwave.yml.tml
```
{{ $versions := "" }}
{{ $versions := readFile "./charts.lock.yaml" | fromYaml }}


releases:
  - name: kube-prometheus
    namespace: monitoring
    chart:
      name: bitnami/kube-prometheus # oci://registry-1.docker.io/bitnamicharts/kube-prometheus
      version: {{ $versions | get "versions.kube-prometheus" "" }}
```

if I want to programatilly check for available updates, I need to run a set of commands (I put it in a Gitlab CI job). Providing an empty chart.lock.yaml makes helmwave create a planfile with latest version of charts.
```
- echo "" > charts.lock.yaml
  - helmwave yml
  - helmwave build
  - cp .helmwave/planfile b
  - "versionsDiff=$(diff a b | grep 'name: .helmwave' || true)"
  - echo "Available updates:"
  - echo $versionsDiff
  - echo "To apply updates, increase versions in charts.lock.yaml"
  - |
    if [ "$versionsDiff" != "" ]; then
      exit 1
    else
      exit 0
    fi
```

as you can see its very home-made, it would be amazing to integrate such feature into helmwave

**Reply by zhilyaev** [reply]
@tony-engineering 
Helmwave shows chart changes in logs. Do you wanna fail the Helmwave build process if the chart version has changed?

**Comment by zhilyaev** [comment]
# Plandir

## V1

**.helmwave/**
  - planfile.yml
  - manifests/
     - nginx@default.yml
     - mongo@prod.yml
  - values/
     - nginx@default/
         - a.yml
         - b.yml
   - stores/
       - nginx@default/
         - vault.yml
         - creds.yml.tpl
   - crds/
      - plan.yml
      - nginx@default.yml
      - mongo@prod.yml

### Deploy with kubectl
```
kubectl -f .helmwave/manifests 
```

### Run the pull model
```
kubectl -f .helmwave/crds 
```


## V2

**.helmwave/**
  - planfile.yml
  - nginx@default/
      - manifests.yml
      - release.yml
      - values/
         - a.yml
         - b.yml
       - stores/
         - vault.yml
         - creds.yml.tpl
   - mongo@prod/
      - manifests.yml
      - release.yml

**Reply by zhilyaev** [reply]
V1

**Reply by zhilyaev** [reply]
V2

**Comment by zhilyaev** [comment]
# helmwave.yml.tpl

Self-render configuration.

## V1

Left 2 steps for render. It's current behavior.

helmwave.yml.tpl -- helmwave yml --> helmwave.yml

## V2
Only 1 file!

helmwave.yml can contain templating. For example [werf.yml](https://werf.io/docs/v2/reference/werf_yaml_template_engine.html), (Pulumi.yaml)[https://www.pulumi.com/blog/pulumi-yaml/]

 You will get a template error in `helmwave build` command.

**Reply by zhilyaev** [reply]
V1

**Reply by zhilyaev** [reply]
V2

**Comment by zhilyaev** [comment]
# Plan behavior

## V1

The current concept is that a plan is a subject on which you can perform actions. Such as deploy a plan, delete a plan, and rollback a plan. 

**It means that if you delete the release from the plan. It won't delete the release.** 

For example, you need to uninstall the release FooBar `helmwave build -t FooBar`. You must generate the plan with only FooBar. Then run `helmwave down` to uninstall FooBar. And then rebuild the plan with all your new stuff.

```mermaid
flowchart LR

subgraph Plan
   release_A
   release_B
end

generate((generate)) --> Plan --> up((up)) & down((down)) & rollback((rollback))

```


## V2

Plan it's what we want to see in a k8s cluster. It means a plan is a list of actions for a deployer.
 `planfile.yaml` will look like:

```yaml
releases:
 a:
   plan: uninstall
 b:
   plan: install
 c:
   plan: rollback
```

```
$ helmwave apply -f planfile
....
Deployed 1/1
Uninstalled 1/1
Rollback 1/1

Everything is ok!
```

Thus, inconsistency of the plan may occur. When the command `helmwave yml` is called again.


```mermaid
flowchart LR
up((up))
 down((down))
  rollback((rollback))

subgraph Plan
   release_A --> down
   release_B --> up
   release_C --> rollback
end

generate((generate)) --> Plan --> apply((apply))

```

## V3

It's like V1. Set the option behavior for helmwave cli. 

- helmwave up --sync --prev-plandir .helmwave_prev --plandir .helmwave
- helmwave sync 

Issues
- You have to keep 2 plans for sync.

## V4 
is coming...

**Reply by zhilyaev** [reply]
V1

**Reply by zhilyaev** [reply]
V2

**Reply by zhilyaev** [reply]
V3

**Comment by zhilyaev** [comment]
# Example v1

```yaml
project: my-platform

# Maps keyed by identity: repositories by alias/host, releases by uniqname
# "name[@namespace[@kubecontext]]" (namespace/context optional — the current
# kube-context is used when omitted).
#
# repositories cover both helm repos (https://) and OCI registries (oci://).
# A value may be a bare URL string, or a full object when auth/flags are needed.
repositories:
  bitnami: https://charts.bitnami.com/bitnami   # bare URL (short form)
  registry.example.com:                          # full form: OCI with creds
    url: oci://registry.example.com
    username: [[ getenv "REGISTRY_USER" "anonymous" ]]
    password: [[ getenv "REGISTRY_PASS" "" ]]

# Defaults for every release via confijer type-defaults ("Release" = the Go type).
# Labels deep-merge into each release (a release's own label wins); values act as
# a default used only when a release declares none of its own.
Release:
  labels:
    common: true
  values:
    - values/common.yml

releases:
  postgres@data:
    labels:
      app: postgres
      tier: db
      env: [[ getenv "ENV" "prod" ]]
    chart:
      name: bitnami/postgresql
      version: 15.x
    # values entries accept any of: {src: url}, bare url, with or without scheme.
    values:
      - values/pg.yml.tpl

  api@app:
    labels:
      app: api
      tier: backend
      env: [[ getenv "ENV" "prod" ]]
    needs:
      releases:
        postgres@data:
          strict: true          # fail if this dependency is filtered out
    chart:
      name: oci://registry.example.com/charts/api
      version: 1.4.2
    values:
      - src: values/api.yml.tpl
    # inline overrides (helm --set style), applied on top of values;
    # keys are dotted paths, values keep their YAML type.
    sets:
      replicaCount: 3
      image.tag: [[ getenv "API_TAG" "1.4.2" ]]
    store:
      - src: extra/netpol.yml

  cache@app:
    labels: { app: redis, tier: cache, env: prod }
    needs:
      # Kubernetes-style label selector inlined into needs: wait for every
      # release it matches.
      matchLabels:
        tier: db
      # matchLabelsExpressions:
      #   - { key: env, operator: In, values: [prod, stg] }
    chart:
      name: bitnami/redis
      version: 20.x

```
