### DISCUSSION TITLE
failed to install "vector@monitoring": create: failed to create: namespaces "monitoring" not found

### DISCUSSION THREAD

**Discussion by angu49** [helmwave/helmwave#599] [Q&A] [answered]
I am trying to create namespaces through Helmwave and the helmwave.yml looks like this

```
version: 0.25.0

# General options
.options: &options
  wait: true
  wait_for_jobs: true
  force: false
  timeout: 10m
  atomic: false
  max_history: 3
  create_namespace: true


releases:
- name: replicator
  namespace: kube-system
  chart: helmwave/kubernetes-replicator
  condition: replicator.enabled
  values:
    # Default
    - environments/default/_.yml
    # For specific ENVIRONMENT
    - environment/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}/_.yml
- name: cert-manager
  condition: cert-manager.enabled
  namespace: cert-manager
  chart: helmwave/cert-manager
  values:
    # Default
    - environments/default/_.yml
    - environment/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}/_.yml
  
- name: vector
  condition: vector.enabled
  namespace: monitoring
  chart: helmwave/vector
  values:
    - environments/default/_.yml
    - environment/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}/_.yml

```
I get the following error when I use helmwave up:
	* failed to install "vector@monitoring": create: failed to create: namespaces "monitoring" not found
	* failed to install "cert-manager@cert-manager": create: failed to create: namespaces "cert-manager" not found
	
Do you know what I am doing wrong?

**Comment by r3nic1e** [comment, marked as answer]
You define general options but don't use them in any of the releases. You should try updating them like that:
```yaml
releases:
- name: replicator
  namespace: kube-system
  <<: *options
  ...
```
