### DISCUSSION TITLE
How to configure helm arguments in the Helmwave releases section?

### DISCUSSION THREAD

**Discussion by MurzNN** [helmwave/helmwave#789] [Q&A] [answered]
I'm deploying the metrics-server using the Helm chart https://github.com/kubernetes-sigs/metrics-server/tree/master/charts/metrics-server - here is the `releases` section:
```yaml
releases:
  - name: metrics-server
    namespace: metrics-server
    create_namespace: true
    chart: metrics-server/metrics-server
    version: 3.11.0
    values:
      - values/metrics-server/values.yaml
```
But to make it work without signed certificates, the `metrics-server` documentation says that I should use the `--kubelet-insecure-tls` flag:

> Kubelet certificate needs to be signed by cluster Certificate Authority (or disable certificate validation by passing --kubelet-insecure-tls to Metrics Server)

But I can't find a way how to pass this flag using Helmwave? Can anybody help with this?

**Comment by MurzNN** [comment]
Seems in the `helmfile` there is `args:` parameter that can do this: https://github.com/helm/charts/issues/14505
```yaml
releases:
  - name: metrics-server
    chart: stable/metrics-server
    version: 2.8.0
    values:
      - image:
          pullPolicy: Always
      - args:
          - --kubelet-insecure-tls
```
But this doesn't work for the `helmwave`.
