### ISSUE TITLE
"installed = false" Helmfile alternative

### ISSUE THREAD

**Issue by needleshaped** [helmwave/helmwave#1022]
**Is your feature request related to a problem? Please describe.**

Document a a way to disable/uninstall specific release, e.g. [here](https://docs.helmwave.app/0.41.x/examples/helmfile-migration/) as compared to Helmfile provided [installed = false](https://helmfile.readthedocs.io/en/latest/#configuration)

P.S. Originally I wrote request about:
> - Inability to declaratively disable=ignore specific release.
>  Use cases: 
>    - Populating `helmwave.yml.tpl` with Helm Charts that are not YET built.
>    - Disabling some releases temporarily.
> - Do not fail `helmwave build` on such disabled releases (e,g, `failed to locate chart`)

...but understood, that _commenting out_ or removing from YML code is the intended way.
Please confirm if I'm right.
This issue will serve as document itself, but a small chapter would benefit the project.

---

**Describe the solution you'd like**

1. Please answer and correct me, if I'm wrong
2. Improve documentation or implement switch similar to `[installed = false` .
3. Consider skipping Helm Chart download for releases, which tags are NOT matched on `helmwave build`.

---

**Describe alternatives you've considered**
- [Tags](https://docs.helmwave.app/latest/examples/tags/) do not allow to isolate release, still fails with  `failed to locate chart`
- Removing code is not an option, as the release may need to be re-enabled, and should not be lost (even in GIT history) until then
- Commenting is a good option.

---

**Additional context**
Helmfile provides `installed = false` https://helmfile.readthedocs.io/en/latest/#configuration

P.S. Thank you for the project! Trying new things, so far can admit, that learning curve compared to Helmfile is steeper.

**Comment by zhilyaev** [comment]
Helmwave has a different vision for planned releases.
Tags are the option to pick releases for manipulation.

```bash
helmwave build -t <group what you want>
helmwave build -t <uniqname>
```

`failed to locate chart` is an error about the path to your chart. 
Could you share your `helmwave.yml` for investigation a problem, please?

**Comment by kittydoor** [comment]
Assuming I am already using tags for logical grouping, what is the proposed approach for gradually deploying a new chart to multiple environments?

```yaml
# helmwave.yml
project: Example
version: "0.41.8"

repositories:
  - name: example
    url: https://example.com

releases:
  - name: example
    chart:
      name: example/example
      version: 1.2.3
    namespace: default
    values:
      # Default
      - values/example/default.yml
      # Overrides for specific ENVIRONMENT
      - values/example/{{ requiredEnv "CI_ENVIRONMENT_NAME" }}.yml
    tags:
      - example

# ... other releases with useful tags
```

For a simple example lets assume that I have 2 environments, dev and prod. I would like to first deploy this chart to dev before the other environments (i.e. prod).

As I'm trying to adopt helmwave, the solution I'm considering going with after submitting this is using helmwave.yml.tpl and a "is_enabled" flag in my custom templating to manage this. Unfortunately it adds a lot of complexity that would be better handled by this tool itself. Specifically, it makes it a lot more "custom tailored" and makes it harder for someone else to read the file and understand how all the pieces connect to each other.

PS: On a similar note of env management, a more tightly knit solution for passing an env to `helmwave build` rather than the proposed requiredEnv CI_ENVIRONMENT_NAME would be a lot neater from a "how polished does this tool feel?" perspective when I show it to other people. If you are interested in a proposal for this, as opposed to the `installed = <condition>` approach please expand the fold below.

<details>
<summary>A not so well thought out example</summary>

`helmwave build --env dev` with a schema change to `helmwave.yml` that allows configuring environments:

```yaml
environments:
  - name: dev
    context: dev
    default: true # default to this env, if --env not specific
    default_namespace: dev-ns # default namespace if not specified in the release
    # deploy all tags by default
  - name: staging 
    context: staging
    default_namespace: staging-ns
    tags:
      - blog
      - app
      - app-v2
      - landing
      # Thus specifying explicitly what is in this env.
  - name: prod
    context: prod
    default_namespace: prod-ns
    tags:
      - blog
      - app
      - landing
      # Thus, keeping the app-v2 tag from being deployed
```
Alternatively `exclude_tags:` can achieve the same effect.

```yaml
  - name: prod
    context: prod
    default_namespace: prod-ns
    exclude_tags:
      - app-v2
```

Arguably it might be simpler to use a `releases: environments: list-of-envs` approach as opposed to `environments: tags: list-of-tags`, keeping the decision from the release perspective.

```yaml
releases:
  - name: app-v2
    chart:
      name: my/app
      version: 1.2.3
    environments:
      - dev
      - staging
```

</details>
