### ISSUE TITLE
Remove the "_" character from the names of the Helm parameters

### ISSUE THREAD

**Issue by konstesting** [helmwave/helmwave#1034]
**Describe the bug**
For example the docs https://docs.helmwave.app/0.41.x/yaml/#repositories describes that we can use the next parameters for **repositories[]**:
- **insecure_skip_tls_verify** 	bool	false
- **pass_credentials_all** 	bool	false

But these parameters doesn't have effect to Helm utility because the [Helm uses only JSON Unmarshaler inside](https://github.com/helm/helm/blob/main/pkg/repo/chartrepo.go#L49-L50).
And for correct working Yaml Marshaller we need to remove "_" characters from the name of parameter, for example:
insecure_skip_tls_verify -> insecureskipverify
pass_credentials_all -> passcredentialsall

**General info (please complete the following information):**

- OS: linux
- Helmwave Version v0.41.1

**To Reproduce**
1. cat helmwave.yml
```
version: "0.32.3"

repositories:
  - name: helm-repo
    url: https://my.company.com/helm-repo/
    insecureskiptlsverify: true
    force: true
...
```
2. `helmwave build`
3.
```
$ cat $HOME/.config/helm/repositories.yaml
apiVersion: ""
generated: "0001-01-01T00:00:00Z"
repositories:
- caFile: ""
  certFile: ""
  insecure_skip_tls_verify: false
  keyFile: ""
  name: helm-repo
  pass_credentials_all: false
  password: ""
  url: https://my.company.com/helm-repo/
  username: ""
```
