### ISSUE TITLE
doesnt exists depends item in plan

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#105]
Suppose that

`helmwave.yml.tpl` contains

```yaml
releases:
  - name: api
     depends_on:
        - db
  - name: db
```

```bash
$ helmwave -t api
[warn] db not found for api
```
