### ISSUE TITLE
Helmwave.yml v1.0.0

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#1107]
project: example
version: 0.0.0

repositories:
  bitnami: https://charts.bitnami.com/bitnami

registries:
  ghcr.io: {}

defaults:
  # Default fields for all releases
  release:
    chart: bitnami/nginx
    namespace: default
    context: my-kube-context

  # Default fields for all registry
  registry:
    insecure: false

  # Default fields for all registry
  repository:
    insecure: false

releases:
  nginx@example@custom-context:
    version: 0.3.0

  nginx@hello: # = nginx@hello@my-kube-context
    version: 0.1.0

  nginx: # = nginx@default@my-kube-context
    version: 0.2.0

**Comment by zhilyaev** [comment]
![Image](https://github.com/user-attachments/assets/53d14930-3c40-4792-8131-48ad2772d1c9)

**Comment by zhilyaev** [comment]
![Image](https://github.com/user-attachments/assets/af38c3bd-4c83-4f93-8476-2fe90343ea17)

**Comment by zhilyaev** [comment]
# Repositories vs Registries?

Merge Repositories & Repositories into one spec?

```yaml
repositories:
  bitnami: https://charts.bitnami.com/bitnami

registries:
  ghcr.io: {}
```

vs


```yaml
repositories:
  bitnami: https://charts.bitnami.com/bitnami
  ghcr.io: oci://ghcr.io
```

**Comment by zhilyaev** [comment]
# Values

```yaml
values:
  - s3://mybucket/config/file.json
  - ../path/to/values.json
  - git+https://github.com/hairyhenderson/gomplate//docs-src/content/functions/env.yml
```

**Comment by zhilyaev** [comment]
# StoreFiles

```yaml
releases:
  app:
    storefiles:
      my:
        src: https://raw.githubusercontent.com/my.store.yml
        render: sops
    values:
      a:
        src: a.values.yml
        render: copy
       b:
         src: b.values.yml
         render: copy
```

## How to call the data from the store?

`$ cat a.values.yml`

```yaml
podLabels:
  name: (ds "store/my").bla
```

## How to call the data from another value?

!!! You can face a problem with cyclic dependencies.

`$ cat b.values.yml`

```yaml
podLabels:
  name: (ds "values/a").bla
```

**Comment by zhilyaev** [comment]
# Defaults
Defaults can be passed by `helmwave.yml` or environment variables. 
helmwave has a lot of features and settings that can interact with each other. 
That's why we want to keep it once inside the `helmwave.yml` defaults section.

Any fields in this section can be passed by ENVIRONMENT VARIABLES.

## Example 

- `export HELMWAVE_DEFAULTS_GOMLATE_RIGHT=']]'`
- `cat helmwave.yml`

```yaml
defaults:
  gomplate:
    left: '[['
    right: ']]'
```

It's equal to

`cat helmwave.yml`
```yaml
defaults:
  gomplate:
    left: '[['
```

**Comment by zhilyaev** [comment]
# Gomplate vs Sprig?
Gomplate!

Sprig must die.

**Comment by zhilyaev** [comment]
# Slice or Map?
Map!

It's prettier for yaml merge and finding the uniqname problems.

**Comment by zhilyaev** [comment]
# Magic Uniqname
Uniqname is just `$release_name@$namespace@kubecontext` in one string. It helps helmwave to understand the destination of your stack.


```yaml
releases:
  nginx@example@custom-context:
    version: 0.3.0

  nginx@hello: # = nginx@hello@my-shell-kube-context
    version: 0.1.0

  nginx: # = nginx@default@my-shell-kube-context
    version: 0.2.0
```

- If kubecontext is empty, helmwave would use your current kubeconfig to understand it.
- If kubecontext is empty, helmwave would use your current kubeconfig to understand it.
- The release name is always required.

**Comment by zhilyaev** [comment]
# [draft] Deploy manifests step-by-step



## Order by weight

> https://github.com/werf/nelm/tree/main#advanced-resource-ordering

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: order-by-weight
  annotations:
    "helmwave.app/weight": "1"
```

## Order by Needs

```yaml
apiVersion: v1
kind: Deployment
metadata:
  name: order-by-weight
  annotations:
    "helmwave.app/needs": "configMap/order-by-weight,<$kind>/<$name>"
```

**Comment by zhilyaev** [comment]
# Levels of abstraction

```mermaid
flowchart TD
    configmap_A & deployment_A & service_A & ingress_A --> helm_chart_A
    configmap_B & deployment_B & service_B & ingress_B --> helm_chart_B
    helm_chart_A --> release_A1 & release_A2 --> helmwave
    helm_chart_B --> release_B1 & release_B2 --> helmwave
```

**Comment by zhilyaev** [comment]
# Deploy releases step-by-step

## Strict needs

```yaml
releases:
  app:
    needs:
       name:
           db: {}
       labels:
           app: db
```

# Smart needs

todo: discuss about sqlite syntax

```yaml
releases:
  app:
    needs:
       rule-name:
         - WHERE namespace = "prod"
```

**Comment by zhilyaev** [comment]
# Client-Side Apply (CSA) vs Server-Side Apply (SSA)

Server-Side Apply!

**Comment by zhilyaev** [comment]
# Pull or Push model CD?
Together!

## Release

```yaml
api: helmwave.app/v1alpha1
kind: Release
spec: …
```

## Repository

```yaml
api: helmwave.app/v1alpha1
kind: Repository
spec: …
```

### Files

```yaml
api: helmwave.app/v1alpha1
kind: FileRef
spec: …
```

```yaml
api: helmwave.app/v1alpha1
kind: Values
spec: …
```

```yaml
api: helmwave.app/v1alpha1
kind: Store
spec: …
```
