### ISSUE TITLE
Support `.Tags` object in values template to get provided tags in `helmwave build`

### ISSUE THREAD

**Issue by Vigilans** [helmwave/helmwave#1113]
**Is your feature request related to a problem? Please describe.**

I want to set different values on a field given the provided tag when running `helmwave build`.

**Describe the solution you'd like**

Like `.Release` object, expose provided tags as `.Tags` object.

**Describe alternatives you've considered**

Render values file from some other engine (like ansible template). But this loses the flexibility in changing value in each `helmwave build` run.

**Comment by zhilyaev** [comment]
It's already working.

```yaml
myTags:
{{ .Release.Tags | toYAML | indent 2 }}
```

helmwave build --template=gomplate

**Comment by Vigilans** [comment]
I am saying `helmwave build --tags <tags>`, and get this tag from yaml file, instead of tags specified in `helmwave.yml`.

**Comment by Vigilans** [comment]
e.g.
`local-path-provisioner`'s value:
```
nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - /var/lib/local-path-provisioner

storageClass:
  defaultClass: <if build with tag local-path-provisioner>
```

`rook-ceph-cluster`'s value:
```
cephFileSystems:
  - storageClass:
      enabled: true
      isDefault: <if build with tag ceph>
```

**Comment by zhilyaev** [comment]
I don't know if using helmwave tags for dynamic value is a good idea. Cause helmwave tags are a meta build argument for helmwave. 

But you can use the next workaround to call HELMWAVE_TAGS that are really defined.

```bash
export MY_CLASS=my-awesome-class
export HELMWAVE_TAGS=$MY_CLASS

helmwave build
```

```yaml
cephFileSystems:
  - storageClass:
      enabled: true
      isDefault: {{ getenv "MY_CLASS" "bla-bla"}} 
```
