### ISSUE TITLE
template with isInstalled FATAL

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#146]
**Describe the bug**

- Helmwave Version 0.12.0-0.12.6

**To Reproduce**

```yaml
releases:
  - name: luntik
    chart:
      name: ./helm
    namespace: {{ env "NAMESPACE" }}
    resetvalues: true
    wait: true
    atomic: true
    values:
    - ./helm/values-{{ env "NAMESPACE" }}.yaml
```

$ helmwave build

**Expected behavior**
render without k8s

**Screenshots**

```
INFO[0000] Building manifests...                        
FATA[0000] Kubernetes cluster unreachable: Get "http://localhost:8080/version?timeout=32s": dial tcp [::1]:8080: connect: connection refused
```
