### ISSUE TITLE
Vault / Secret Manager 

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#159]
**Is your feature request related to a problem? Please describe.**

It allows pass vault data to `values.yaml/helmwave.yml`

**Describe the solution you'd like**

$ vault kv get -format=json secret/webapp/prod
```json
{
    "pass": "12345"
}
```

`values.yaml`

```yaml
replica: 1
env:
  password: {{ vault 'secret/webapp/prod', 'pass'  }}
```

$ helmwave plan

```yaml
replica: 1
env:
  password: "12345"
```

**Describe alternatives you've considered**

gomplate #103 ?

https://docs.gomplate.ca/datasources/#using-vault-datasources

**Additional context**

Btw, I prefer use vault-operator. Because it is safer.

**Comment by zhilyaev** [comment]
@r3nic1e Could you show example how to use it. Here or Docs.

**Comment by zhilyaev** [comment]
for helmwave 0.14.0

Step 1. Create next secret:
```bash
$ aws secretsmanager create-secret --name hello/foobar --secret-string '{"foo":"bar"}'
```

**helmwave.yml**

```yaml
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

template:
  gomplate:
    enabled: true
    data:
      sources:
        secret:
          url:
            scheme: aws+sm
            path: 'hello/foobar'

releases:
  - name: app
    chart:
      name: bitnami/nginx
    namespace: test
    values:
      - vaules-secret.yaml
```


**vaules-secret.yaml**

```yaml
secret: {{ ds "secret" }}
```


### helmwave build

**vaules-secret.yaml**

```yaml
secret: {"foo":"bar"}
```

**Comment by zhilyaev** [comment]
And also for vault it wiil

helmwave.yml

```yaml
template:
  gomplate:
    enabled: true
    data:
      sources:
        secret:
          url:
            scheme: vault
            path: 'hello/foobar'
```
