### ISSUE TITLE
helmwave hangs on "up" with 0.14

### ISSUE THREAD

**Issue by sandroden** [helmwave/helmwave#163]
**Describe the bug**
While trying to understand how to use helmwave I run:

```
helmwave build
helmwave  up
```
and `healwave` hang up.
`helmwave.yml` is as simple as:

```
project: node-setup

repositories:
- name: jetstack
  url: https://charts.jetstack.io 

releases:
- name: cert-manager
  namespace: cert-manager
  chart:
    name: jetstack/cert-manager
    version: v1.5.3
  createnamespace: true
```
setting log leverl to debug I see:

```
[🙃 aka INFO]: 🛥 Sync releases...
[🙃 aka INFO]: 🛥 "cert-manager@cert-manager" deployig... 
[🤷 aka DEBUG]: getting history for release cert-manager
[🤷 aka DEBUG]: 🧐 Release "cert-manager@cert-manager" does not exist. Installing it now.
[🤷 aka DEBUG]: creating 1 resource(s)
[🤷 aka DEBUG]: creating 38 resource(s)
[🤷 aka DEBUG]: creating 1 resource(s)
[🤷 aka DEBUG]: creating 1 resource(s)
[🤷 aka DEBUG]: creating 1 resource(s)
[🤷 aka DEBUG]: creating 1 resource(s)
[🤷 aka DEBUG]: Watching for changes to Job cert-manager-startupapicheck with timeout of 0s
[🤷 aka DEBUG]: Add/Modify event for cert-manager-startupapicheck: ADDED
[🤷 aka DEBUG]: cert-manager-startupapicheck: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
[🤷 aka DEBUG]: Add/Modify event for cert-manager-startupapicheck: MODIFIED
[🤷 aka DEBUG]: cert-manager-startupapicheck: Jobs active: 1, jobs failed: 0, jobs succeeded: 0

```
** General info:**

- OS: Ubuntu 20.04 
- microk8s 1.21 + helm 3.5.0
- Helmwave Version 0.14.0
My planfile:

```
project: node-setup
version: 0.14.0
template: null
repositories:
- name: jetstack
  url: https://charts.jetstack.io
  username: ""
  password: ""
  certfile: ""
  keyfile: ""
  cafile: ""
  insecureskiptlsverify: false
  passcredentialsall: false
  force: false
releases:
- store: {}
  chart:
    name: jetstack/cert-manager
    cafile: ""
    certfile: ""
    keyfile: ""
    insecureskiptlsverify: false
    keyring: ""
    password: ""
    passcredentialsall: false
    repourl: ""
    username: ""
    verify: false
    version: v1.5.3
  name: cert-manager
  namespace: cert-manager
  description: ""
  depends_on: []
  values: []
  tags: []
  timeout: 0s
  maxhistory: 0
  createnamespace: true
  resetvalues: false
  recreate: false
  force: false
  atomic: false
  cleanuponfail: false
  subnotes: false
  disablehooks: false
  disableopenapivalidation: false
  waitforjobs: false
  wait: false
  skipcrds: false
  devel: false
  reusevalues: false
```

I don't have a `helmwave render` command...

Is there something wrong in my commands?
