### ISSUE TITLE
allow_failure

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#168]
Depends on

```
releases:
- name: a
  allow_failure: false

- name: b
  depends_on: 
   - a
```

if `a` deploy failed `b` will not deploy.
