### ISSUE TITLE
Manage namespaces as well

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#232]
Helmwave already manages helm repositories and helm releases. I guess kubernetes namespaces - the only thing left that is required to deploy helm chart.

The main reason to manage namespaces is to append labels to it (e.g. prometheus or sidecars enablers).

Example configuration:
```yaml
repositories: []

namespace:
  - name: test-ns
    annotations: {}
    labels: {}

releases:
  - name: redis-a
    namespace: test-ns # created by helmwave before release
    
  - name: redis-b
    namespace: ns-test # created by bundled helm during release
    createnamespace: true
```

**Comment by zhilyaev** [comment]
IDK how to do it well.

`helm --create-ns` will create clear ns without any labels, annotations or extra data. And helm doesn't provide way to custom it.

**Comment by zhilyaev** [comment]
Also helm can install namespace  as regular resource. 

```yaml
apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: {{ .Values.name }}
  name: {{ .Values.name }}
```
