### ISSUE TITLE
Refactor fields to snake_case

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#264]
Current yaml:

```yaml
insecureskiptlsverify: false
createnamespace: false
resetvalues: false
```

with snake_case
```yaml
insecure_skip_tls_verify: false
create_namespace:  false
reset_values: false
allow_failure: true
```
