### ISSUE TITLE
--file command-line option does not change working directory for resolving relative paths in release.values

### ISSUE THREAD

**Issue by Blobson** [helmwave/helmwave#359]
**Describe the bug**
Not quite sure if it's a bug or expected behavior, but using `helmwave build --file deploy/helmwave.yml` result in `WARNING: skipping: local file not found` issues. 
It seems that helmwave is looking for values files inside current working directory rather than inside `deploy` directory where `helmwave.yml` is located.

** General info (please complete the following information):**

- OS: any
- Helmwave Version: 0.19.3

**To Reproduce**

1. Create `deploy/helmwave.yml` file:
```yaml
project: test-project
version: 0.0.1

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: test-server
    chart:
      name: bitnami/nginx
      version: 13.1.0
    values:
      - nginx.yml
```
2. Create `deploy/nginx.yml` file:
```yaml
commonAnnotations:
  test-app: test-server
```
3. Run `helmwave build -f deploy/helmwave.yml`
4. Look for warnings in the STDOUT:
```
[🙈 aka WARNING]: skipping: local file not found
	values src: nginx.yml
	values dst: /tmp/values/nginx@test-server/fd90bbf380aa67ee14ea968bdff7f1960af89e28.yml
	release: nginx@test-server
```

**Expected behavior**
I would expect helmwave to look for values files inside `deploy` directory.

**Comment by zhilyaev** [comment]
Nowadays we have no '--context' flag. Maybe we should add this option.

But today, you can fix it like that

```yaml
project: test-project

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    namespace: test-server
    chart:
      name: bitnami/nginx
      version: 13.1.0
    values:
      - {{ filepath.Dir (requiredEnv "HELMWAVE_TPL") }}/nginx.yml
```


```bash
export HELMWAVE_TPL=deploy/helmwave.yml.tpl
export HELMWAVE_TEMPLATER=gomplate
helmwave build --yml
```
