### ISSUE TITLE
add strict flag: manage skip behavior for values

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#377]
**Is your feature request related to a problem? Please describe.*
#359 discussion 

**Describe the solution you'd like**

```yaml
values:
- src: hello.yaml
  strict: true
```
