### ISSUE TITLE
Add render flag: manage templating for values

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#378]
**Is your feature request related to a problem? Please describe.*
#359 discussion 

**Describe the solution you'd like**

```yaml
values:
- src: hello.yaml
  render: true
```
