### ISSUE TITLE
Error trying to log in to a public OCI registry

### ISSUE THREAD

**Issue by flaamjab** [helmwave/helmwave#410]
I have Helm charts published to GitHub Container Registry. I have specified the registry in helmwave.yml:
```yaml
registries:
  - host: ghcr.io
```

The `releases` list looks like this:
```yaml
releases:
  - name: platform
    chart: oci://ghcr.io/cheetah-game-platform/charts/platform
    <<: *options
```

When I run `helmwave build` it errors with:
```
[🤬 aka FATAL]: one of goroutines in waitgroup sent error: 1 error occurred:
        * failed to login in helm registry: Get "https://ghcr.io/v2/": denied
```

It works fine if I provide a token in the `password` field, but that is undesirable.

Am I missing something or is there a way to bypass this behavior? I'm using version 0.21.0.

**Comment by zhilyaev** [comment]
chart.version is requred for OCI

**Comment by zhilyaev** [comment]
[helm login](https://helm.sh/docs/topics/registries/) required the login and password/token for the host. You shouldn't login for public charts. But Helmwave is looking registries for your oci chart. That feature is keeping your repositories and registries correct.

**Comment by zhilyaev** [comment]
@flaamjab  fixed at #409

**Comment by zhilyaev** [comment]
I check on that helmwave.yml

```yaml
registries:
- host: ghcr.io

releases:
- name: platform
  namespace: test
  chart:
    name: oci://ghcr.io/cheetah-game-platform/charts/platform
    version: 0.0.11


```
