### ISSUE TITLE
Ability to render correctly charts that use .Capabilities.APIVersions

### ISSUE THREAD

**Issue by samavasi** [helmwave/helmwave#447]
**Is your feature request related to a problem? Please describe.**
There are community charts that use in their templates Capabilities that require server side validation to properly work, eg apiVersion using .Capabilities.APIVersions to check k8s cluster compatibility
NOTE it seems to fail on first time installs (is there a diff on rendering templates for helmwave plan in greenfield deploy vs upgrade?)

**Describe the solution you'd like**
It would be nice if possible to have option during helmwave plan phase to render the chart templates using helm upgrade --dryrun instead of helm template for the above to work. Please correct me if wrong on the helm template assumption, or would there be any reason why dryrun upgrade wouldnt work well with helmwave?

**Comment by r3nic1e** [comment]
Helmwave uses `helm upgrade --dry-run`for generating manifests.
Could you please provide an example helmwave.yml that renders incorrectly?

**Comment by samavasi** [comment]
it fails for first time deployment of eg the renovate helm chart that uses above `.Capabilities.APIVersions`, subsequent upgrades are ok. sample helmwave yml as per bellow:

```
version: 0.22.2

repositories:
  - name: renovate
    url: https://docs.renovatebot.com/helm-charts

releases:
   - allow_failure: false
     chart:
       name: renovate/renovate
       version: 32.159.5
     create_namespace: true
     name: renovate
     namespace: renovate
     pending_release_strategy: uninstall
     tags:
       - renovate
     timeout: 600s
     wait: true

```
trying helmwave build -> output below:
```
[💩 aka ERROR]: ❌ can't get manifests: failed to install "renovate@renovate": execution error at (renovate/templates/cronjob.yaml:8:6): 

 ERROR: You must have at least batch/v1beta1 to use CronJob
	release: renovate@renovate
[🤬 aka FATAL]: one of goroutines in waitgroup sent error: 1 error occurred:
	* failed to install "renovate@renovate": execution error at (renovate/templates/cronjob.yaml:8:6): 

 ERROR: You must have at least batch/v1beta1 to use CronJob
```
