### ISSUE TITLE
Allow override for go template delimiters in values 

### ISSUE THREAD

**Issue by derbeneviv** [helmwave/helmwave#453]
**Is your feature request related to a problem? Please describe.**
Let's imagine we have a service which requires values to be passed with go templates in strings.  
Examples are: consul, vault, alertmanager, etc...  
AND we want to template it using helmwave.
Currently we would need to escape inner go templates like that:  
```
var1: "text {{ `{{ do not render it by helmwave }}` }}
var2: "text {{ render it by helmwave }}"
```

which will result in 
```
var1: "text {{ do not render it by helmwave }}
var2: "text rendered_value"
```
This requires re-writing existing values which can be frustrating and can make migration to helmwave harder

**Describe the solution you'd like**
We can use https://pkg.go.dev/text/template#Template.Delims for go template and override delimeters for helmwave  
In that case we can write smth like:  
```
# in helmwave.yaml.tpl
releases:
- name: chartname
  left_delimeter: "<<"
  right_delimeter: ">>"
  values:
    - values.yaml
```
in values.yaml
```
var1: "text {{ do not render it by helmwave }}"
var2: "text << render it by helmwave >>"
```

**Comment by zhilyaev** [comment]
i prefer:

```
releases:
- name: chartname
  delimeters:
   right: ">>"
   left: "<<"
  values:
    - values.yaml
```

**Comment by zhilyaev** [comment]
We have 3 scope for templater.

- Global
- Specific release
- Specific values.


On the last one It will look like:

```yaml
releases:
- name: chartname
  values:
    - src: values.yaml
        delimeters:
          right: ">>"
          left: "<<"
```

**Comment by r3nic1e** [comment]
I think moving delimeters (as well as all other template settings) cannot be set on release level due to possible confusion.

There are a lot of things that are templated:

1. `helmwave.yml.tpl` - we control it
2. values files - we control it
3. release chart - we have no control over it

So for this code newcomers may think that we control chart manifests templating:

```yaml
releases:
- name: chartname
  delimeters:
   right: ">>"
   left: "<<"
  values:
    - values.yaml
```

So I think there are 2 options:

1. Make it easier to understand but ugly:
```yaml
valuesTemplateSettings:
  delimiter_left: "<<"
  delimiter_right: ">>"

releases:
- name: chartname
  valuesTemplateSettings:
    delimiter_right: ">>"
    delimiter_left: "<<"
  values:
    - src: values.yaml
      delimiter_left: "<<"
      delimiter_right: ">>"
```
2. Support only settings at per-values level. This way it will be easy to implement (really much much easier) and relatively easy to use (yaml anchors or `helmwave.yml.tpl` can reduce copy-paste work).

**Comment by zhilyaev** [comment]
I will continue second way

```
dels: *dels
  delimiter_left: "<<"
  delimiter_right: ">>"

releases:
- name: name
  values:
    - src: values.yaml
      <<:*dels
      delimiter_left: "<<"
      delimiter_right: ">>"
```
