### ISSUE TITLE
Add support for depending on group of releases

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#484]
Sample helmwave.yml:

```yaml
releases:
  - name: db1
    tags: [db]
  - name: db2
    tags: [db]
  - name: app
    depends_on:
      - tag: db
        operator: any
```

`operator` can be either `any` or `all`.
