### ISSUE TITLE
Jsonschema requires too many fields

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#488]
helmwave.yml:
```yaml
project: Test02

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    chart:
      name: bitnami/nginx
      version: 13.1.7
    namespace: test
    create_namespace: true
```

helmwave.yml in json:
```json
{
  "project": "Test02",
  "repositories": [
    {
      "name": "bitnami",
      "url": "https://charts.bitnami.com/bitnami"
    }
  ],
  "releases": [
    {
      "name": "nginx",
      "chart": {
        "name": "bitnami/nginx",
        "version": "13.1.7"
      },
      "namespace": "test",
      "create_namespace": true
    }
  ]
}
```

Errors:

- Required properties are missing from object: username, password, certFile, keyFile, caFile, insecure_skip_tls_verify, pass_credentials_all, force.
  Schema path: https://github.com/helmwave/helmwave/pkg/plan/plan-body#/properties/repositories/items/required

- Property 'version' has not been defined and the schema does not allow additional properties.
  Schema path: https://github.com/helmwave/helmwave/pkg/plan/plan-body#/properties/releases/items/properties/chart/additionalProperties

- Required properties are missing from object: CaFile, CertFile, KeyFile, InsecureSkipTLSverify, Keyring, Password, PassCredentialsAll, RepoURL, Username, Verify, Version.
  Schema path: https://github.com/helmwave/helmwave/pkg/plan/plan-body#/properties/releases/items/properties/chart/required

- Required properties are missing from object: version, registries.
  Schema path: https://github.com/helmwave/helmwave/pkg/plan/plan-body#/required
