### ISSUE TITLE
Use strict=true for values by default

### ISSUE THREAD

**Issue by alexandrovas** [helmwave/helmwave#534]
In my opinion, it would be more intuitive if strict=true by default when parsing values. The absence of some value files is a more unique case that must be explicitly specified in the config:

```yml
releases:
  - name: test
    values:
      - src: values.yaml
        strict: false
```
