### ISSUE TITLE
Provide a flag to pass `--set-file` to the helm deployment

### ISSUE THREAD

**Issue by meysam81** [helmwave/helmwave#547]
**Is your feature request related to a problem? Please describe.**
When deploying using bare `helm` in the terminal, you're able to pass `--set-file` for the values that the content is residing in a file. AFAIK the helm itself doesn't provide the option to pass those values from a values file and if that's the case, it means that I'll not be able to provide them at all using `helmwave`. If there is such a feature, please point me in the right direction and otherwise, please add the feature to the upcoming releases :pray: .

**Describe the solution you'd like**
I want to be able to have the `--set-file` flag implemented in the `helmwave`.

**Describe alternatives you've considered**
I know of no alternative at the moment.

**Additional context**
As an example, here's one scenario that `--set-file` is very useful:

```bash
$ helm upgrade -i -n linkerd-management --create-namespace linkerd \
    --set-file identityTrustAnchorsPEM=./certs/ca.crt \
    --set-file identity.issuer.tls.crtPEM=/certs/issuer.crt \
    --set-file identity.issuer.tls.keyPEM=/certs/issuer.key \
    --set identity.issuer.crtExpiry=$(date -d '+8760 hour' +"%Y-%m-%dT%H:%M:%SZ") \
    -f values/linkerd.yml \
    --atomic \
    linkerd/linkerd2
```

**Comment by meysam81** [comment]
@r3nic1e @zhilyaev @r-mironov @teodor-i

**Comment by r3nic1e** [comment]
@meysam81 you can use `readFile` in values:

```yaml
identityTrustAnchorsPEM: {{ readFile "./certs/ca.crt" | quote }}
identity:
  issuer:
    crtExpiry: {{ now | date_modify "+8760h" | date "2006-01-02T15:04:05Z" }}
    tls:
      crtPEM: {{ readFile "./certs/issuer.crt" | quote }}
      keyPEM: {{ readFile "./certs/issuer.key" | quote }}
```

Does that suit you?
