### ISSUE TITLE
Add support for autorollbacks based on prometheus metrics

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#712]
There is a cool helm plugin that rolls back if prometheus expression is true - https://github.com/ContainerSolutions/helm-monitor

I think it would be cool to support these types of rollbacks with this configuration:

```yaml
monitors:
  - name: main-monitor
    type: prometheus
    url: http://localhost:9090
    expr: |
      up == 1
    interval: 10s
    success_threshold: 5
    failure_threshold: 10
    timeout: 2m # fail if it flaps between success and failure for so long
    
releases:
  - name: bla
    monitors:
      - name: main-monitor
```

Probably supporting only prometheus will be okay for PoC. ES and others can be added later if required
