### ISSUE TITLE
tags vs. depends_on

### ISSUE THREAD

**Issue by antonvigo** [helmwave/helmwave#734]
We've faced with the problem of preventing optional dependencies to be deployed. So we have several products described in helmwave.yml and some of them are dependent from some infrastructure services like redis, postgresql etc. And in some cases these dependencies are acutal for all environments. But sometimes prod deployment is quite "independent". There is no any common pattern. That's why it's very important to have flexible built-in mechanism for such situations. From my point of view it would be great to prevent installation of optional dependencies with tag feature. Actually I've expected that because it seems to be quite obvious. But as it was mentioned in the TG-channel, unfortunately tags don't have influence on the installation of servant services specified in depends_on block. Even if they are optional. For example applying this piece of code with `helmwave build -t app_only` will install both mentioned services:
```
  - name: app
    chart:
      name: oci://host/path/to/app
    depends_on:
      - name: redis
        optional: true
    tags:
      - app_only
    values:
      - ...

  - name: redis
    chart:
      name: bitnami/redis
    tags:
      - redis
      - infrastructure
    values:
      - ...
```

So it would be awesome for tags to have precedence over depends_on section. But taking into account possible unexpected issue it is also convenient to have current behavior as default and some special (boolean) environment variable like `HELMWAVE_TAGS_ARE_BOSS` to let tags be "the Boss". 

All existing workarounds make me suffer and don't let me sleep well. :smile: So I hope this feature will be added.
Thank you!
