### ISSUE TITLE
Helmwave for GitOps

### ISSUE THREAD

**Issue by r3nic1e** [helmwave/helmwave#736]
Operator:

- [x] https://github.com/helmwave/helmwave/issues/740
- [x] https://github.com/helmwave/helmwave/issues/739
- [x] https://github.com/helmwave/helmwave/issues/742

ArgoCD plugin:

- [x] https://github.com/helmwave/helmwave/issues/743
- [x] https://github.com/helmwave/helmwave/issues/744

Helmwave should be more friendly to GitOps. So it would be awesome for helmwave to:

- Work as an operator with it's own CRD
- Work as an ArgoCD plugin

<details>
<summary>CRD design</summary>

```yaml
apiVersion: helmwave.app/v1alpha1
kind: HelmwaveManifest
spec:
  src: git@github.com/helmwave/docs.git//docs/examples/blabla
  credentials:
    - git:
        secretRef:
          name: blabla-secret
  args:
    yml: true
    file: helmwave1.yml
    tpl: helmwave1.yml.tpl
    tags:
      - nginx-a
      - nginx-b
    matchAllTags: false
  jobLimit: 3 # default - operator settings (1)
  persistentVolumeClaimRef:
    name: helmwave-pvc
  podMetadata:
    annotations:
      vault-agent-injector: "true"
  podSpec: # optional
    restartPolicy: Never
    containers:
      - name: helmwave # optional, default - helmwave
        image: ghcr.io/helmwave/helmwave:0.32.0 # optional, default - operator settings
        envFrom:
          - secretRef:
              name: helmwave-envs-secret
          - configMapRef:
              name: helmwave-envs-cm
          env:
            - name: BLABLA
              value: BLABLA
status:
  conditions:
  - lastTransitionTime: "2023-06-08T14:23:14Z"
    lastUpdateTime: "2023-06-08T14:23:14Z"
    message: helmwave build succeeded # failed
    reason: Build
    status: "True" # "False"
    type: Build
  - lastTransitionTime: "2023-07-11T13:05:07Z"
    lastUpdateTime: "2023-07-11T13:05:07Z"
    message: helmwave up succeeded # failed
    reason: Up
    status: "True" # "False"
    type: Up
  observedGeneration: 3
  phase: Succeeded
  releases:
    - nginx-a@nginx
    - nginx-b@nginx
  totalReleasesCount: 8
  syncedReleasesCount: 1
  status: succeeded # failed # in progress
```

</details>

```mermaid
flowchart TD
  CRD --create event--> get_lock
  CRD --change event--> get_lock

  subgraph Operator
    get_lock[get k8s lock] --> spawn_job_for_crd[spawn job for the CRD]

    drop_job_for_crd[drop jobs for the CRD exceeding jobLimit] --> release_lock[release k8s lock]
  end

  subgraph OperatorJob
    subgraph HelmwaveOperatorRun[`helmwave operator crd-1233dbfx`]
      helmwave_build[run `helmwave build`] -.update status..-> CRD
      helmwave_build --> helmwave_up[run `helmwave up`]
      helmwave_up -.update status..-> CRD
    end
  end

  spawn_job_for_crd --> OperatorJob
  OperatorJob --> drop_job_for_crd
```
