### ISSUE TITLE
Identical names for the chart and the directory with values. Problem with chart installation.

### ISSUE THREAD

**Issue by networkcat89** [helmwave/helmwave#763]
The main essence of the problem: if we name the directory the same as the chart that we fetch remotely, then helmwave throws an error because it cannot find the chart locally. I assume that the check for the local chart happens first, causing helmwave to error out and not search for the chart remotely.

** General info (please complete the following information):**

- OS: K8s cluster on Ubuntu 20.04
- Helmwave Version 0.32.1

**To Reproduce**

directory structure, when the problem manifests:
```
total 40
drwxrwxr-x  5 oem oem 4096 Oct 18 09:01 ./
drwxr-xr-x 17 oem oem 4096 Oct 18 09:00 ../
drwxrwxr-x  2 oem oem 4096 Oct 17 18:05 .cicd_templates/
drwxrwxr-x  8 oem oem 4096 Oct 18 08:49 .git/
-rw-rw-r--  1 oem oem   17 Oct 17 12:34 .gitignore
-rw-rw-r--  1 oem oem  864 Oct 18 08:35 .gitlab-ci.yml
-rw-rw-r--  1 oem oem 1471 Oct 18 08:30 helmwave.yml
drwxrwxr-x  2 oem oem 4096 Oct 17 17:50 ingress-nginx/
-rw-rw-r--  1 oem oem   31 Oct 17 17:50 README.md
-rw-rw-r--  1 oem oem  793 Oct 17 17:48 .yamllint
```

helmwave.yml:
```
project: DeployViaHelmwave
version: "0.32.1"

.options: &options
  create_namespace: true
  atomic: true
  wait: true
  timeout: 5m
  max_history: 3
  show_notes: false

repositories:
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx

releases:
  - name: ingress-nginx
    <<: *options
    namespace: ingress-nginx
    chart:
      name: ingress-nginx/ingress-nginx
      version: 4.8.2
    values:
      - ./ingress-nginx/values.yaml
```
run:
helmwave build

got error:

![2023-10-17_14-50](https://github.com/helmwave/helmwave/assets/129379027/104fe35b-7992-4835-b059-3d83450c5e2d)

To solve the problem, you need to rename the 'ingress-nginx' directory to a name different from the chart name.
