### ISSUE TITLE
The error "The filename, directory name, or volume label syntax is incorrect" occurs when running helmwave build on Win

### ISSUE THREAD

**Issue by dpr-dev** [helmwave/helmwave#805]
**Describe the bug**

When trying to build the release on Windows computers, we get an error when using oci repositories. Only reproduces on windows. Running the same script in **wsl** gives the expected result

Example config

```
version: "0.32.3"  

registries:
  - host: us-docker.pkg.dev
    username: oauth2accesstoken
    password: {{ requiredEnv "GOOGLE_ACCESS_TOKEN"}}

releases: 
  - name: sql-auth-proxy
    chart: 
      name: oci://us-docker.pkg.dev/p-r3o-ci-cd/helm/sql-auth-proxy
      version: 0.1.0
    namespace: db
    create_namespace: true 
    wait: true
    max_history: 5
```

**General info (please complete the following information):**
- OS: Windows
- Helmwave Version: 0.32.3, 0.33.0

**To Reproduce**
Just try to build the template above (probably the same behavior with other registry artifacts like github)

**Expected behavior**
Template is rendered, plan is created

**Screenshots / Stdout**
<img width="1130" alt="image" src="https://github.com/helmwave/helmwave/assets/23157659/6a701b33-b1de-456c-928b-b2959e106e41">
