### ISSUE TITLE
Document values templating.

### ISSUE THREAD

**Issue by zystem** [helmwave/helmwave#860]
I have the next helmwave.yml
```
releases:
  - name: karma
    namespace: monitoring
    chart: wiremind/karma
    version:
    values:
      - envs/dev.yaml
      - src: karma.yaml
        render: sprig
```
dev.yaml
```
nginx:
  domain:
    private: dev.local
```
karma.yaml
```
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - karma.{{ .Values.nginx.domain.private }}
```
then I try run 
`CI_ENVIRONMENT_NAME=dev helmwave build`
I got
`failed to render template: failed to render template: template: tpl:15:22: executing "tpl" at <.Values.nginx.domain.private>: can't evaluate field Values in type struct { Release release.Config }`
Nothing in the documentation can help me understand what I am doing wrong. There are no examples for this case. No explanation of how it should work. Only useless string `If you've ever written helm charts, then you're already familiar with it.`

**Comment by zhilyaev** [comment]
@zystem check the docs
https://docs.helmwave.app/0.35.x/tpl/

> There is a different context between helm and helmwave. You can't pass variables from helmwave to your
> helm chart templates. You should use helmwave to render values of your chart.

**Comment by zhilyaev** [comment]
use `store` or `common vars` for achieve it

**Comment by zhilyaev** [comment]
## helmwave.yml

```yaml
releases:
- name: karma
  namespace: monitoring
  chart: wiremind/karma
  store:
    domain: dev.local
  values:
  - karma.yml
```


## karma.yml

```yaml
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - karma.{{ .Release.Store.domain }}
```
