### ISSUE TITLE
post-build script double run 

### ISSUE THREAD

**Issue by w33dw0r7d** [helmwave/helmwave#863]
**Describe the bug**
post-build scrip running twice  

**General info (please complete the following information):**

- OS: linux
- Helmwave Version 0.32.4/0.35.3

**To Reproduce**

1.  Create helmwave.yml like this 
```
version: 0.32.4

registries:
  - host: ghcr.io
releases:
  - name: test
    namespace: default
    depensd_on:
    - test2
    chart:
      name: oci://ghcr.io/nginxinc/charts/nginx-ingress
      version: 1.0.0
    lifecycle:
      post_build:
        - allow_failure: false
          args:
            - -c
            - echo AAAAAA
          cmd: /bin/bash
      pre_build:
        - allow_failure: false

          args:
            - -c
            - echo BBBBBB
          cmd: /bin/bash
```
2. run `helmwave up --build helmwave.yml`

**Expected behavior**
post-build run once

**Screenshots / Stdout**
```
[🤮 aka TRACE]: adding flag to action context.Context
	name: build
	value: true
[🤮 aka TRACE]: adding flag to action context.Context
	name: log-level
	value: trace
[🤷 aka DEBUG]: timeout is not set, defaulting to 5m
	release: test@default
[🙃 aka INFO]: 🔨 Building releases...
[🙃 aka INFO]: 🔨 Building values...
[🙃 aka INFO]: 🔨 no values provided
	release: test@default
[🙃 aka INFO]: 🔨 Building repositories...
[🤮 aka TRACE]: 🗄 helm repository.yaml: /root/.config/helm/repositories.yaml
[🙃 aka INFO]: 🔨 Building registries...
[🤷 aka DEBUG]: 🗄 This chart will download via OCI
	release: test@default
[🤷 aka DEBUG]: 🗄 found releases that depend on registries
	registry: ghcr.io
	releases:
	  - test@default
[🙃 aka INFO]: 🗄 registry has been added to the plan
	registry: ghcr.io
[🤷 aka DEBUG]: Public OCI chart. Skipping helm login.
	registry: ghcr.io
[🙃 aka INFO]: 🔨 Building charts...
[🙃 aka INFO]: Pulled: ghcr.io/nginxinc/charts/nginx-ingress:1.0.0
[🙃 aka INFO]: Digest: sha256:ecf2529ccec167f777a8cbf3118961571f3ea8cc14614f02784d8f9feeb56128
[🙃 aka INFO]: 🔨 Building manifests...
[🙃 aka INFO]: ❎ skipping updating dependencies for remote chart
	release: test@default
[🙃 aka INFO]: 🩼 Running pre-build hooks...
[🙃 aka INFO]: 🩼 running hook...
	cmd: /bin/bash
	args:
	  - -c
	  - echo BBBBBB
[🙃 aka INFO]: BBBBBB
[🙃 aka INFO]: Pulled: ghcr.io/nginxinc/charts/nginx-ingress:1.0.0
[🙃 aka INFO]: Digest: sha256:ecf2529ccec167f777a8cbf3118961571f3ea8cc14614f02784d8f9feeb56128
[🤷 aka DEBUG]: I'll dry-run.
	release: test@default
[🤷 aka DEBUG]: WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
[🙃 aka INFO]: 🩼 Running post-build hooks...
[🙃 aka INFO]: 🩼 running hook...
	cmd: /bin/bash
	args:
	  - -c
	  - echo AAAAAA
[🙃 aka INFO]: AAAAAA
[🤮 aka TRACE]: ---
# Source: nginx-ingress/templates/controller-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-nginx-ingress
  namespace: default
  labels:
    helm.sh/chart: nginx-ingress-1.0.0
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.3.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: nginx-ingress/templates/controller-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-nginx-ingress
  namespace: default
  labels:
    helm.sh/chart: nginx-ingress-1.0.0
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.3.0"
    app.kubernetes.io/managed-by: Helm
data:
---
# Source: nginx-ingress/templates/controller-leader-election-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: test-nginx-ingress-leader-election
  namespace: default
  labels:
    helm.sh/chart: nginx-ingress-1.0.0
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.3.0"
    app.kubernetes.io/managed-by: Helm
---
# Source: nginx-ingress/templates/rbac.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-nginx-ingress
  labels:
    helm.sh/chart: nginx-ingress-1.0.0
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.3.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - list
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - update
- apiGroups:
  - k8s.nginx.org
  resources:
  - virtualservers
  - virtualserverroutes
  - globalconfigurations
  - transportservers
  - policies
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - k8s.nginx.org
  resources:
  - virtualservers/status
  - virtualserverroutes/status
  - policies/status
  - transportservers/status
  verbs:
  - update
---
# Source: nginx-ingress/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: test-nginx-ingress
  labels:
    helm.sh/chart: nginx-ingress-1.0.0
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.3.0"
    app.kubernetes.io/managed-by: Helm
subjects:
- kind: ServiceAccount
  name: test-nginx-ingress
  namespace: default
roleRef:
  kind: ClusterRole
  name: test-nginx-ingress
  apiGroup: rbac.authorization.k8s.io
---
# Source: nginx-ingress/templates/controller-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-nginx-ingress-controller
  namespace: default
  labels:
    helm.sh/chart: nginx-ingress-1.0.0
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  selector:
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
---
# Source: nginx-ingress/templates/controller-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-nginx-ingress-controller
  namespace: default
  labels:
    helm.sh/chart: nginx-ingress-1.0.0
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ingress
      app.kubernetes.io/instance: test
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-ingress
        app.kubernetes.io/instance: test
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9113"
        prometheus.io/scheme: "http"
    spec:
      serviceAccountName: test-nginx-ingress
      automountServiceAccountToken: true
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - image: nginx/nginx-ingress:3.3.0
        name: nginx-ingress
        imagePullPolicy: "IfNotPresent"
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        - name: https
          containerPort: 443
          protocol: TCP
        - name: prometheus
          containerPort: 9113
        - name: readiness-port
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /nginx-ready
            port: readiness-port
          periodSeconds: 1
          initialDelaySeconds: 0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsUser: 101 #nginx
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
            add:
            - NET_BIND_SERVICE
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        args:
          - -nginx-plus=false
          - -nginx-reload-timeout=60000
          - -enable-app-protect=false
          - -enable-app-protect-dos=false
          - -nginx-configmaps=$(POD_NAMESPACE)/test-nginx-ingress
          - -ingress-class=nginx
          - -health-status=false
          - -health-status-uri=/nginx-health
          - -nginx-debug=false
          - -v=1
          - -nginx-status=true
          - -nginx-status-port=8080
          - -nginx-status-allow-cidrs=127.0.0.1
          - -report-ingress-status
          - -external-service=test-nginx-ingress-controller
          - -enable-leader-election=true
          - -leader-election-lock-name=test-nginx-ingress-leader-election
          - -enable-prometheus-metrics=true
          - -prometheus-metrics-listen-port=9113
          - -prometheus-tls-secret=
          - -enable-service-insight=false
          - -service-insight-listen-port=9114
          - -service-insight-tls-secret=
          - -enable-custom-resources=true
          - -enable-snippets=false
          - -include-year=false
          - -disable-ipv6=false
          - -enable-tls-passthrough=false

          - -enable-preview-policies=false
          - -enable-cert-manager=false
          - -enable-oidc=false
          - -enable-external-dns=false
          - -ready-status=true
          - -ready-status-port=8081
          - -enable-latency-metrics=false
---
# Source: nginx-ingress/templates/controller-ingress-class.yaml
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  labels:
    helm.sh/chart: nginx-ingress-1.0.0
    app.kubernetes.io/name: nginx-ingress
    app.kubernetes.io/instance: test
    app.kubernetes.io/version: "3.3.0"
    app.kubernetes.io/managed-by: Helm
spec:
  controller: nginx.org/ingress-controller

	release: test@default
[🙃 aka INFO]: ✅  manifest done
	release: test@default
[🙃 aka INFO]: 🔨 Building graphs...
[🤷 aka DEBUG]: graph draw options
	min-word-length: 12
	min-cell-width: 3
	max-cell-width: 16
	graph-width: 0
	max-word-length: 12
[🙃 aka INFO]: show graph:
┌───────────────┐
│ test@default  │
└───────────────┘

[🙃 aka INFO]: 🏗 Plan
	repositories:
	  -
	registries:
	  - ghcr.io
	releases:
	  - test@default
[🙃 aka INFO]: 🆚 Diff manifests in the kubernetes cluster
[🙃 aka INFO]: getting charts diff
	release: test@default
[🙃 aka INFO]: 🩼 Running pre-build hooks...
[🙃 aka INFO]: 🩼 running hook...
	args:
	  - -c
	  - echo BBBBBB
	cmd: /bin/bash
[🙃 aka INFO]: BBBBBB
[🙃 aka INFO]: Pulled: ghcr.io/nginxinc/charts/nginx-ingress:1.0.0
[🙃 aka INFO]: Digest: sha256:ecf2529ccec167f777a8cbf3118961571f3ea8cc14614f02784d8f9feeb56128
[🤷 aka DEBUG]: I'll dry-run.
	release: test@default
[🤷 aka DEBUG]: WARNING: This chart or one of its subcharts contains CRDs. Rendering may fail or contain inaccuracies.
[🙃 aka INFO]: 🩼 Running post-build hooks...
[🙃 aka INFO]: 🩼 running hook...
	cmd: /bin/bash
	args:
	  - -c
	  - echo AAAAAA
[🙃 aka INFO]: AAAAAA
[🙃 aka INFO]: 🆚 ❎ no changes
	release: test@default
[🙃 aka INFO]: 🆚 🌝 Plan has no changes
[🙃 aka INFO]: 🏗 Planfile is ready!
[🤷 aka DEBUG]: ✅ yaml version is equal to binary version
[🙃 aka INFO]: 🏗 Plan
	repositories:
	  -
	registries:
	  - ghcr.io
	releases:
	  - test@default
[🙃 aka INFO]: 🗄 sync repositories...
[🤮 aka TRACE]: 🗄 helm repository.yaml: /root/.config/helm/repositories.yaml
[🙃 aka INFO]: 🗄 sync registries...
[🤷 aka DEBUG]: Public OCI chart. Skipping helm login.
	registry: ghcr.io
[🙃 aka INFO]: 🛥 sync releases...
[🤷 aka DEBUG]: Deploying releases with limited parallelization
	limit: 1
[🙃 aka INFO]: 🛥 deploying...
	release: test@default
[🤷 aka DEBUG]: getting history for release test
[🤷 aka DEBUG]: preparing upgrade for test
[🤷 aka DEBUG]: performing update for test
[🤷 aka DEBUG]: creating upgraded release for test
[🤷 aka DEBUG]: checking 8 resources for changes
[🤷 aka DEBUG]: Looks like there are no changes for ServiceAccount "test-nginx-ingress"
[🤷 aka DEBUG]: Patch ConfigMap "test-nginx-ingress" in namespace default
[🤷 aka DEBUG]: Looks like there are no changes for ConfigMap "test-nginx-ingress-leader-election"
[🤷 aka DEBUG]: Looks like there are no changes for ClusterRole "test-nginx-ingress"
[🤷 aka DEBUG]: Looks like there are no changes for ClusterRoleBinding "test-nginx-ingress"
[🤷 aka DEBUG]: Looks like there are no changes for Service "test-nginx-ingress-controller"
[🤷 aka DEBUG]: Patch Deployment "test-nginx-ingress-controller" in namespace default
[🤷 aka DEBUG]: Looks like there are no changes for IngressClass "nginx"
[🤷 aka DEBUG]: updating status for upgraded release for test
[🙃 aka INFO]: ✅
	release: test@default
[🙃 aka INFO]: Releases Success 1 / 1
[🙃 aka INFO]: Monitors Success 0 / 0
```
