### ISSUE TITLE
Helm Git support

### ISSUE THREAD

**Issue by mhkarimi1383** [helmwave/helmwave#870]
**Is your feature request related to a problem? Please describe.**
I want to install some charts that are not having any repository

**Describe the solution you'd like**
Something like https://github.com/aslafy-z/helm-git will be awesome

**Describe alternatives you've considered**
Cloning git repo then install from path

**Additional context**

**Comment by zhilyaev** [comment]
I see that's is better

```yaml
lifecycle:
  pre_build:
    - git clone https://github.com/helmwave/unit-test-oci.git

releases:
  - name: test
    namespace: test
    chart: ./unit-test-oci

```
