### ISSUE TITLE
false positive release duplicate for multi context

### ISSUE THREAD

**Issue by zhilyaev** [helmwave/helmwave#910]
```yaml
releases:
  # {{ range $c := $clusters }}
  - name: {{ $name }}
    <<: *options
    chart: oci://registry-1.docker.io/bitnamicharts/bla-bla
    context: {{ .context}}
  # {{- end }} finish
```
