### ISSUE TITLE
Kubernetes objects using Release.Revision variable in labels always get redeployed

### ISSUE THREAD

**Issue by dsaintbase1** [helmwave/helmwave#921]
**Describe the bug**
I'm using a Truecharts helm chart for deploying one of my applications.
Truecharts set the label `helm-revision: {{ .Release.Revision | quote }}` [in their common library](https://artifacthub.io/packages/helm/truecharts-library-common-oci/common?modal=template&template=lib/metadata/_allLabels.tpl), which is then injected in most if not all of their Kubernetes object templates for applications. 

.Release.Revison always increment after each new release as documented in Helm's website: https://helm.sh/docs/chart_template_guide/builtin_objects/

The issue related to helmwave: after the first deployment of a Truecharts release using helmwave, all the objects are constantly being changed after new builds due to helmware trying to set the value of the `helm-revision` label to 1:
```
sftpgo, sftpgo, Deployment (apps) has changed:
...
      app: sftpgo-7.0.4
      app.kubernetes.io/instance: sftpgo
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sftpgo
      app.kubernetes.io/version: 2.5.6
-     helm-revision: "52"
+     helm-revision: "1"
      helm.sh/chart: sftpgo-7.0.4
      release: sftpgo
    name: sftpgo
    namespace: sftpgo
  spec:
...
          app: sftpgo-7.0.4
          app.kubernetes.io/instance: sftpgo
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: sftpgo
          app.kubernetes.io/version: 2.5.6
-         helm-revision: "52"
+         helm-revision: "1"
          helm.sh/chart: sftpgo-7.0.4
          pod.lifecycle: permanent
          pod.name: main
          release: sftpgo
      spec:
...
sftpgo, sftpgo, Service (v1) has changed:
...
      app: sftpgo-7.0.4
      app.kubernetes.io/instance: sftpgo
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sftpgo
      app.kubernetes.io/version: 2.5.6
-     helm-revision: "52"
+     helm-revision: "1"
      helm.sh/chart: sftpgo-7.0.4
      release: sftpgo
      service.name: main
    name: sftpgo
    namespace: sftpgo
...
sftpgo, sftpgo-backupdirectory, PersistentVolumeClaim (v1) has changed:
...
      app: sftpgo-7.0.4
      app.kubernetes.io/instance: sftpgo
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sftpgo
      app.kubernetes.io/version: 2.5.6
-     helm-revision: "52"
+     helm-revision: "1"
      helm.sh/chart: sftpgo-7.0.4
      release: sftpgo
    name: sftpgo-backupdirectory
    namespace: sftpgo
  spec:
...
```

Running `helmwave up` will always redeploy the Kubernetes objects including the Deployment which restart the application which makes it out of service for a short time. 

I couldn't find a parameter in the docs that could perhaps cimcurvent this behaviour with helmwave, some I'm opening this bug report.
 
**General info (please complete the following information):**

- OS: macOS
- Helmwave Version: 0.36.4

**To Reproduce**
Steps to reproduce the behaviour:

1. Deploy a release based on a Truecharts (ex: https://truecharts.org/charts/stable/sftpgo/)
2. Redeploy it again and notice that helmwave wants to overwrite the value of the `helm-revision` label to 1.

**Expected behaviour**
helmwave should ignore the value of the `helm-revision` after running a build. The value of the label should always increment.

**Screenshots / Stdout**
See above.

Let me know if you have any questions & want more details. Thanks!
Regards,

**Comment by r3nic1e** [comment]
Could you also share your `helmwave.yml` file?

**Comment by dsaintbase1** [comment]
Here @r3nic1e:

```
project: debug-sftpgo
version: "0.36.4"

# OCI: modern way to get chart from registry
registries:
  - host: tccr.io

.options: &options
  #namespace: my-namespace
  create_namespace: true
  wait: true
  wait_for_jobs: true
  force: false
  timeout: 10m
  max_history: 3 # best practice

releases:
#################################
#                               #
#      sftpgo
#                               #
#################################
  - name: sftpgo
    chart:
      name: oci://tccr.io/truecharts/sftpgo
      version: 7.0.4
    namespace: sftpgo
    tags: [sftpgo]
    <<: *options
```
