### ISSUE TITLE
Do not include comments while templating values

### ISSUE THREAD

**Issue by mhkarimi1383** [helmwave/helmwave#953]
**Is your feature request related to a problem? Please describe.**
When I want to have some comments in my values (and containing things like `requiredEnv`) helmwave tries to also template the comments

**Describe the solution you'd like**
Ignoring comments in values (remove them before running the templating logic)

**Describe alternatives you've considered**
Using hooks

**Additional context**

**Comment by zhilyaev** [comment]
Hi mate!

For commenting go template you have to use `{{/* getenv "HELLO_WORLD" */}}`
For commenting yaml you have to use `# HelloWorld`.

Thus, it is expected behavior. It's the feature. It's useful when you want to generate documentations inside:

```yaml
{{ range $env := $envs }}
###### {{ $env }}
{{ range $app := $apps }}
# {{ $app }}
- env: {{ $env }}
  app: {{ $app }}
{{ end }}
```

it will transform into

```yaml
###### PROD
# api
- env: prod
  app: api 

# web
- env: prod
  app: web 


###### DEV

# api
- env: dev
  app: api

# web
- env: dev
  app: web
```
